trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /triggers-schedule.yml

schedules:
- cron: "0 18 * * Mon,Thu"
  displayName: Regression Testing (Mon,Thu)
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    which bash
    echo Hello $name
  displayName: Multiline Bash script
  env:
    name: Microsoft

- script: echo Hello world!
  displayName: Say hello